services:
  rustapp:
    container_name: rust-api
    image: hazardzero/rust-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
    ports:
      - '8080:8080'
      - '8050:8050'
    depends_on:
      - postgresdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 15s

  postgresdb:
    container_name: postgresdb
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - pgvolume:/var/lib/postgres/data    

volumes:
  pgvolume: {}