services:
  rustapp:
    container_name: rust-api
    image: hazardzero/rust-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:17.4-alpine3.21
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - pgvolume:/var/lib/postgres/data    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  pgvolume: {}