version: '3.9'

services:
  rustapp:
    container_name: rust-api
    image: hazardzero/rust-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - '8080:8080'
    depends_on:
      - postgresdb
      
  postgresdb:
    container_name: db
    image: postgres:17.4-alpine3.21
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - pgvolume:/var/lib/postgres/data

volumes:
  pgvolume: {}
